#!/usr/bin/env python3
"""
Fix Notion Database Configuration
Tests current database IDs and creates new ones if needed
"""

import os
import sys
import logging
sys.path.append('/Users/chungty/Projects/abm-research/src')

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

def test_current_databases():
    """Test if current database IDs are accessible"""
    print("🔍 Testing current database IDs...")

    # Import after path setup
    from abm_research.integrations.notion_client import NotionClient

    try:
        notion_client = NotionClient()

        print(f"📋 Current database configuration:")
        for db_name, db_id in notion_client.database_ids.items():
            if db_id:
                print(f"  ✅ {db_name}: {db_id}")
            else:
                print(f"  ❌ {db_name}: Not configured")

        # Try to test database access
        print("\n🧪 Testing database access...")

        if notion_client.database_ids.get('accounts'):
            try:
                # Test accounts database query
                print("  Testing accounts database...")
                result = notion_client.find_existing_account("Test Company")
                print(f"  ✅ Accounts database accessible")
            except Exception as e:
                print(f"  ❌ Accounts database error: {e}")

        if notion_client.database_ids.get('contacts'):
            try:
                # Test contacts database query
                print("  Testing contacts database...")
                result = notion_client.find_contact_by_linkedin("https://linkedin.com/in/test")
                print(f"  ✅ Contacts database accessible")
            except Exception as e:
                print(f"  ❌ Contacts database error: {e}")

        return True

    except Exception as e:
        print(f"❌ Error initializing Notion client: {e}")
        return False

def create_new_databases():
    """Create new ABM databases from scratch"""
    print("\n🏗️  Creating new ABM databases...")

    from abm_research.integrations.notion_client import NotionClient

    try:
        # Initialize client
        notion_client = NotionClient()

        # We need a parent page ID to create databases
        # Let's try to create them in the root workspace
        parent_page_id = None

        print("📄 Please provide a Notion page ID where databases should be created.")
        print("💡 You can get this from any Notion page URL (the 32-character ID)")
        print("   Example: https://notion.so/My-Page-abc123...def789")

        parent_page_id = input("Enter parent page ID (or press Enter to skip): ").strip()

        if not parent_page_id:
            print("⚠️  No parent page provided. Cannot create databases.")
            return False

        # Clean up the page ID (remove hyphens if present)
        parent_page_id = parent_page_id.replace('-', '')

        # Create databases
        print("Creating ABM databases...")
        databases = notion_client.create_abm_workspace(parent_page_id)

        print("\n✅ Successfully created databases:")
        for db_name, db_id in databases.items():
            print(f"  {db_name}: {db_id}")

        # Update .env file
        print("\n📝 Updating .env file with new database IDs...")
        update_env_file(databases)

        return True

    except Exception as e:
        print(f"❌ Error creating databases: {e}")
        return False

def update_env_file(databases):
    """Update .env file with new database IDs"""
    env_file_path = "/Users/chungty/Projects/abm-research/.env"

    # Read current .env file
    env_vars = {}
    try:
        with open(env_file_path, 'r') as f:
            for line in f:
                if '=' in line and not line.strip().startswith('#'):
                    key, value = line.strip().split('=', 1)
                    env_vars[key] = value
    except FileNotFoundError:
        print("⚠️  .env file not found, creating new one")

    # Update database IDs
    db_mapping = {
        'accounts': 'NOTION_ACCOUNTS_DB_ID',
        'contacts': 'NOTION_CONTACTS_DB_ID',
        'trigger_events': 'NOTION_TRIGGER_EVENTS_DB_ID',
        'partnerships': 'NOTION_PARTNERSHIPS_DB_ID',
        'intelligence': 'NOTION_INTELLIGENCE_DB_ID'
    }

    for db_name, db_id in databases.items():
        if db_name in db_mapping:
            env_var = db_mapping[db_name]
            env_vars[env_var] = db_id
            print(f"  ✅ {env_var}={db_id}")

    # Write updated .env file
    with open(env_file_path, 'w') as f:
        f.write("# ABM Research System Environment Variables\n")
        f.write("# Generated by fix_notion_databases.py\n\n")

        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")

    print(f"✅ Updated {env_file_path}")

def main():
    """Main execution"""
    print("🔧 NOTION DATABASE CONFIGURATION FIX")
    print("=" * 50)

    # Test current databases
    current_working = test_current_databases()

    if current_working:
        print("\n✅ Current databases are working!")
        choice = input("\nDo you want to recreate databases anyway? (y/N): ")
        if choice.lower() != 'y':
            print("✅ No changes needed. Databases are working.")
            return

    # Create new databases
    print("\n🔄 Current databases are not working. Let's create new ones.")
    success = create_new_databases()

    if success:
        print("\n🎉 Database setup complete!")
        print("💡 Please restart your application to use the new database IDs.")
    else:
        print("\n❌ Database setup failed.")
        print("💡 Please check your Notion integration permissions and try again.")

if __name__ == "__main__":
    main()